name = "MARLDynamics_in_Julia"
uuid = "a8e4631f-d272-4450-861c-ed7131ebf4a0"
authors = ["lisa.kauck@tum.de"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
